config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }, controllers: { registrations: "user_registrations" }


  resources :products do
  resources :comments

end

  resources :products do
  resources :orders

end

resources :users

resources :payments

  get 'simple_pages/about'
  get 'simple_pages/contact'
  get 'simple_pages/index'
  post 'simple_pages/thank_you'
  get 'simple_pages/landing_page'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'simple_pages#landing_page'
  post 'payments/create'
  resources :orders, only: [:index, :show, :create, :destroy]

  mount ActionCable.server => '/cable'




end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
  has_many :products, through: :line_items
  has_one :user
  has_one :order, through: :user
  

  def total_price_cart
    line_items.to_a.sum { |item| item.total_price_line_items }
  end

  def line_items_count
    line_items.to_a.sum { |item| item.line_items_count }
  end

  def created_at_asc
    line_items.created_at_asc
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include CurrentCart
  before_action :set_cart, only: [:create, :destroy, :index, :show]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.create(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end



  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    if @cart.id == session[:cart_id] || @cart.id != session[:cart_id]
      session[:cart_id] = nil

    respond_to do |format|
      format.html { redirect_to cart_path }
      format.json { head :no_content }
    end
  end
end



  private
    # Use callbacks to share common setup or constraints between actions.


    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end

    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to root_path, notice: "That cart doesn't exist"
end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<tr>
  <td>Cart_id:<%= cart.id %></td>
  <td>User_id:<%= cart.user_id %></td>
  <td><%= link_to 'Show', cart %></td>
  <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
  <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/_show.html.erb
<div class="container shopping_cart_container">

  <div class="row">
      <div class="col"></div>
      <div class="col">name</div>
      <div class="col">price</div>
      <div class="col">amount</div>
      <div class="col">change amount</div>
      <div class="col">line item total</div>
  </div>

<div>
<% @cart.line_items.created_at_asc.each do |line_item| %>

  <br>

  <div class="row static">
      <div class="col">
        <div class="img-fluid" id="shopping_cart_img"><%= image_tag("#{line_item.product.image_url}") %></div>
      </div>

      <div class="col">
        <%= line_item.product.name %>
      </div>

      <div class="col">
        <%= number_to_currency(line_item.product.price, unit: :£) %>
      </div>

      <div class="col">
        <%= line_item.quantity %>
      </div>

      <div class="col">
        <a class="btn btn-sm btn-outline-primary"<%= link_to '-', line_item, method: :delete, remote: true %></a>
        <a class="btn btn-sm btn-outline-primary"<%= link_to '+', line_item_path(line_item.id), :method => :put, remote: true %></a>
      </div>

      <div class="col">
        <%= number_to_currency(line_item.total_price_line_items, unit: :£) %>
      </div>
  </div>

<%end%>
</div>

  <div class="row">
      <div class="col"></div>
      <div class="col"></div>
      <div class="col"></div>
      <div class="col"></div>
      <div class="col"></div>
      <div class="col">Cart Total:<%= number_to_currency(@cart.total_price_cart, unit: :£) %></div>
  </div>
</div>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
     <%= render @carts %>



  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Shopping Cart</h1>

<% if @cart.line_items.any? %>

<%= render 'show' %>

<div>
  <%= link_to 'Empty Cart', @cart, method: :delete, data: { confirm: 'Are you sure?' } %>
</div>
<br>
<div>
  <%= link_to('continue shopping', products_path, class: "btn btn-sm btn-primary", type: "submit", style: "color:white") %>
</div>
<br>
<% else %>

  <%= link_to('start shopping', products_path, class: "btn btn-sm btn-primary", type: "submit", style: "color:white") %>

<% end %>

<% if user_signed_in? && @cart.line_items.any?%>

<div class = "payment_button">
  <%= form_with(url: '/payments/create', remote: true) do |form| %>
  <%= form.hidden_field :cart_id, value: @cart.id %>
  <%= render partial: "shared/stripe_checkout_button" %>
  <% end %>
</div>

<% else %>

<% if @cart.line_items.any?%>

  <%= button_to('Login to pay', new_user_session_path, type: "button", class: "btn btn-sm btn-info", style: "color:white") %>

<% end %>
<% end %>