config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }, controllers: { registrations: "user_registrations" }


  resources :products do
  resources :comments

end

  resources :products do
  resources :orders

end

resources :users

resources :payments

  get 'simple_pages/about'
  get 'simple_pages/contact'
  get 'simple_pages/index'
  post 'simple_pages/thank_you'
  get 'simple_pages/landing_page'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'simple_pages#landing_page'
  post 'payments/create'
  resources :orders, only: [:index, :show, :create, :destroy]

  mount ActionCable.server => '/cable'




end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title>Duke.Wellington.Example.Web.Shop</title>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= csrf_meta_tags %>
</head>

<body>

    <% if notice %>
        <p id="notice" class="alert alert-primary"><%= notice %></p>
    <% end %>

    <% if alert %>
        <p id="alert" class="alert alert-primary"><%= alert %></p>
    <% end %>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
       <%= link_to "Duke.Wellington.Example.Web.Shop", simple_pages_landing_page_path, class: "nav-link" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "About", simple_pages_about_path, class: "nav-link" %>
      </li>

      <li class="nav-item">
        <%= link_to "Products", products_path, class: "nav-link" %>
      </li>

      <li class="nav-item">
         <%= link_to "Orders", orders_path, class: "nav-link" %>
      </li>

      <li class="nav-item">
        <%= link_to "Contact", simple_pages_contact_path, class: "nav-link" %>
      </li>
    </ul>



  <div class="navbar_cart">
     <%= link_to cart_path(@cart), class:"navbar-item button is-warning" do%>
              <span class="icon is-small">
                <i class="fa fa-shopping-cart"></i>
     <% end %>

     <span id="line_items_count"><%= @cart.line_items_count %></span>
  </div>

    <ul class="navbar-nav ml-auto">

      <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "nav-link") %>
          </li>

        <% else %>
            <li class="nav-item">
              <%= link_to('Login', new_user_session_path, class: "nav-link") %>
            </li>
        <% end %>
    </ul>

      <%= form_with(url: products_path, method: 'get', local: true) do |form| %>
      <%= form.text_field :q, id: 'q', value: params[:q] %>
      <%= form.submit 'Search' %>

      <% if signed_in? && current_user.admin? %>
        <td>Admin: <%= current_user.first_name %> <%= current_user.last_name %></td>
      <% elsif signed_in? %>
        <td>User: <%= current_user.first_name %> <%= current_user.last_name %></td>
      <% else%>
        No user logged in.
      <% end %>
    <% end %>

  </div>
</nav>

<div id="yield">
    <%= yield %>
</div>

<!-- Footer -->

<footer class="page-footer font-small special-color-dark pt-4">

    <!-- Footer Elements -->
    <div class="container">

      <!-- Social buttons -->
      <ul class="list-unstyled list-inline text-center">
        <li class="list-inline-item">
          <a class="btn-floating btn-fb mx-1">
            <i class="fab fa-facebook-f"> </i>
          </a>
        </li>
        <li class="list-inline-item">
          <a class="btn-floating btn-tw mx-1">
            <i class="fab fa-twitter"> </i>
          </a>
        </li>
        <li class="list-inline-item">
          <a class="btn-floating btn-gplus mx-1">
            <i class="fab fa-google-plus-g"> </i>
          </a>
        </li>
        <li class="list-inline-item">
          <a class="btn-floating btn-li mx-1">
            <i class="fab fa-linkedin-in"> </i>
          </a>
        </li>
        <li class="list-inline-item">
          <a class="btn-floating btn-dribbble mx-1">
            <i class="fab fa-dribbble"> </i>
          </a>
        </li>
      </ul>
      <!-- Social buttons -->

    </div>
    <!-- Footer Elements -->

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2019 Copyright:
      <a href="#"> Duke.Wellington</a>
    </div>
    <!-- Copyright -->

  </footer>

  <!-- Footer -->



</body>
</html>